### ISSUE TITLE
PipelineContext.StageID doesn't adapt to the current pipeline stage

### ISSUE THREAD

**Issue by tomkerkhove** [tomasr/pipelinetesting#4]
When executing a pipeline the `PipelineContext.StageID` always returns the value of `Guid.Empty`.

Here is the code I've used to reproduce this.

```
        var receivePipelineBuilder = Pipelines.Receive();
        receivePipelineBuilder.WithValidator(new MyPipelineComponent());
        var pipelineWrapper = receivePipelineBuilder.End();
        pipelineWrapper.Execute(message);
```

**Comment by tomkerkhove** [comment]
I've had a look at your code and I've noticed that you pass an instance of `PipelineContext` to `IPipeline.Execute(<context>);`.

Seems like you have to rely on the implementation of the `Execute`, is that correct? That would mean that this is not possible? If I can lend you a hand, feel free to ping me.

**Comment by tomasr** [comment]
Version 1.2.2 is now up on nuget.org with the changes.

**Comment by tomkerkhove** [comment]
Thank you very much by the way!
